"""RailNet Comprehensive Claim-to-Evidence Verification and Reproducibility Runner.

Enforces the strict verification chain:
CLAIM -> EVIDENCE -> REPRODUCTION METHOD/COMMAND -> EXPECTED RESULT -> ACTUAL RESULT -> EVIDENCE TIER -> STATUS

Executes testable reproduction commands, audits parameters against physically
demonstrated artifacts, downgrades unverified claims to ASSUMPTION or MODELLED,
and outputs a machine-readable JSON verification matrix.

Usage:
    python scripts/verify_all_claims.py
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


CLAIMS_DATABASE = [
    {
        "claim_id": "CLM-01",
        "category": "NVM / ReRAM Density",
        "claim": "ReRAM 3D Crossbar achieves 80 Mbit/mm2 (10 MB/mm2) storage density",
        "claimed_value": "80.0 Mbit/mm2",
        "source": "Academic Literature (Theoretical 4F2 Crossbar without peripheral overhead)",
        "reproduction_command": "python hardware/research/ppa_model.py",
        "expected_result": "Model outputs 80.0 Mbit/mm2 as theoretical academic baseline",
        "actual_result": "80.0 Mbit/mm2 modeled in academic track; commercial silicon reality is 20.0 Mbit/mm2 (4x lower)",
        "evidence_tier": "MODELLED (Academic Literature Projection)",
        "hardware_verified": False,
        "status": "MODELLED_ONLY (DOWNGRADED FROM VERIFIED)",
        "notes": "Academic crossbar papers omit sense amplifiers, charge pumps, and decoders (macro efficiency 48%)."
    },
    {
        "claim_id": "CLM-02",
        "category": "NVM / ReRAM Silicon Reality",
        "claim": "Commercial 22nm eReRAM achieves ~20 Mbit/mm2 (2.5 MB/mm2) macro density",
        "claimed_value": "20.0 Mbit/mm2",
        "source": "Commercial Foundry 22nm eReRAM Macro Datasheets (TSMC 22ULL / UMC 22nm)",
        "reproduction_command": "python hardware/research/ppa_model.py",
        "expected_result": "Model uses 20.0 Mbit/mm2 for commercial track and predicts 572 mm2 die for Gemma 1B (2 chiplets)",
        "actual_result": "Confirmed in ppa_model.py; requires 2 chiplets for Gemma 1B and 5 chiplets for Llama 3B",
        "evidence_tier": "SILICON-MEASURED (Commercial Foundry IP Specifications)",
        "hardware_verified": True,
        "status": "FOUNDRY_IP_SPEC_VERIFIED",
        "notes": "Proves monolithic die for 1B+ models exceeds reticle limits; multi-chiplet packaging is mandatory."
    },
    {
        "claim_id": "CLM-03",
        "category": "NVM / ReRAM Energy",
        "claim": "Commercial 22nm eReRAM read energy is 0.55 pJ/bit (4.4 pJ/byte)",
        "claimed_value": "0.55 pJ/bit",
        "source": "Silicon-proven eReRAM test chips (including bitline capacitance and sense-amp energy)",
        "reproduction_command": "python hardware/research/ppa_model.py",
        "expected_result": "Calculates 7.14 mJ/token at 100 t/s (0.7W) for Gemma 1B in commercial silicon",
        "actual_result": "Energy calculated at 7.14 mJ/token (0.7 W); 2.5x higher than unproven academic 0.20 pJ/bit model",
        "evidence_tier": "SILICON-MEASURED (Commercial Foundry IP)",
        "hardware_verified": True,
        "status": "FOUNDRY_IP_SPEC_VERIFIED",
        "notes": "Academic 0.20 pJ/bit is an assumption; 0.55 pJ/bit is silicon-proven reality."
    },
    {
        "claim_id": "CLM-04",
        "category": "ASIC Clock Frequency",
        "claim": "RailNet Stage-B pipelined adder achieves 200 MHz timing closure in SkyWater 130nm",
        "claimed_value": "200.0 MHz (5.0 ns period)",
        "source": "Architectural target set in hardware/asic/openlane/config.json (CLOCK2_PERIOD = 5.0)",
        "reproduction_command": "None (OpenSTA post-route timing analysis not run)",
        "expected_result": "OpenSTA sign-off report with zero negative slack at 200 MHz with SPEF extraction",
        "actual_result": "NO OpenSTA run; NO parasitic SPEF extracted; 200 MHz is unproven architectural target",
        "evidence_tier": "THEORETICAL (ARCHITECTURAL ESTIMATE / SDC TARGET)",
        "hardware_verified": False,
        "status": "UNVERIFIED_TARGET (DOWNGRADED FROM VERIFIED)",
        "notes": "130nm planar CMOS wire RC delays across multi-tile grid require post-route CTS verification."
    },
    {
        "claim_id": "CLM-05",
        "category": "FPGA Clock Frequency",
        "claim": "RailNet accelerator achieves 83.79 MHz routed Fmax on Lattice ECP5-85F 40nm FPGA",
        "claimed_value": "83.79 MHz routed (11.935 ns critical path) for 4-tile grid; 15.39 MHz for full BF16 tile",
        "source": "results/fpga_pnr_results.json generated by yowasp-nextpnr-ecp5 physical P&R",
        "reproduction_command": "python -c \"import json; d=json.load(open('results/fpga_pnr_results.json')); t=d['targets']['railnet_top_2x2_ecp5']; print('status:', t.get('status'), '| fmax:', t.get('achieved_fmax_mhz'))\"",
        "expected_result": "railnet_top_2x2 places and routes, reporting Fmax >= 80.0 MHz",
        "actual_result": "NOT REPRODUCED. railnet_top_2x2 does not place and route: nextpnr-ecp5 aborts with \"ERROR: IO 's_axis_tvalid' is unconstrained in LPF\". ecp5_versa.lpf constrains only the clocks, reset, 4 LEDs and PCIe refclk/perst - no AXI-Stream or AXI-Lite pin is constrained. The 83.79 MHz figure has no completed routing run behind it in this tree. Individual tiles do route: stagea_bram 209.12 MHz (0 DSP), stageb_int8 157.80 MHz, full_int8_tile 95.50 MHz.",
        "evidence_tier": "NOT REPRODUCED (P&R aborts)",
        "hardware_verified": False,
        "status": "UNSUBSTANTIATED (grid does not route; per-tile P&R numbers stand)",
        "notes": "The grid's AXI ports are internal interfaces to railnet_pcie_wrapper.v, not chip pins, so a standalone pinned P&R of the grid is the wrong target. Either constrain the AXI pins, or run it out-of-context with --lpf-allow-unconstrained and label the result an internal-block estimate."
    },
    {
        "claim_id": "CLM-06",
        "category": "RTL Zero DSP Gather",
        "claim": "RailNet Stage-A integer gather consumes exactly 0 hardware multipliers (0 DSPs)",
        "claimed_value": "0 DSP blocks",
        "source": "ECP5 and Xilinx synthesis reports for stagea_bram / stage_a_int8_bram",
        "reproduction_command": "python -c \"import json; d=json.load(open('results/rtl_synth.json')); print('Stage-A DSP count:', d['tiles']['stagea_bram']['summary']['DSP'])\"",
        "expected_result": "0 DSP blocks utilized in Stage-A gather",
        "actual_result": "0 DSP blocks consumed (100% adder carry-chains and LUTRAM)",
        "evidence_tier": "SYNTHESIZED (STD-CELL / FPGA TECH-MAPPED)",
        "hardware_verified": True,
        "status": "VERIFIED_IN_SYNTHESIS",
        "notes": "Core mathematical transformation verified: Fubini distributive gather eliminates multipliers."
    },
    {
        "claim_id": "CLM-07",
        "category": "PCIe Programming Speedup",
        "claim": "PCIe Bulk DMA provides 720x faster weight programming than in-band CSR MMIO",
        "claimed_value": "720.0x speedup ratio",
        "source": "Analytical latency model: (3 x 150ns MMIO writes) / (2 bytes / 3.2 GB/s DMA)",
        "reproduction_command": "python benchmarks/benchmark_hardware_bottlenecks.py",
        "expected_result": "720.0x theoretical speedup printed in benchmark output",
        "actual_result": "720.0x confirmed as an analytical mathematical ratio; ZERO physical PCIe hardware tested",
        "evidence_tier": "THEORETICAL (ANALYTICAL MATHEMATICAL MODEL)",
        "hardware_verified": False,
        "status": "MODELLED_ONLY (DOWNGRADED FROM HARDWARE MEASURED)",
        "notes": "Requires physical PCIe endpoint card, XDMA IP, and Linux kernel driver to measure real throughput."
    },
    {
        "claim_id": "CLM-08",
        "category": "PCIe Hardware Bridge",
        "claim": "PCIe Runtime Driver communicates with physical hardware accelerator",
        "claimed_value": "Hardware communication via /dev/railnet_user and /dev/railnet_h2c_0",
        "source": "railnet/runtime/pcie.py RailNetPCIeDriver",
        "reproduction_command": "python -c \"from railnet.runtime.pcie import RailNetPCIeDriver; d=RailNetPCIeDriver('test'); print('Hardware:', d.is_hardware, 'Bridge:', type(d.bridge).__name__)\"",
        "expected_result": "Physical PCIe endpoint responds over MMIO and DMA",
        "actual_result": "Falls back to MockPCIeBridge (Python simulation object) because /dev/* does not exist",
        "evidence_tier": "SIMULATED (Software Mock Bridge)",
        "hardware_verified": False,
        "status": "MOCK_ONLY_NO_HARDWARE",
        "notes": "MockPCIeBridge is a software test double; it provides zero physical hardware evidence."
    },
    {
        "claim_id": "CLM-09",
        "category": "ASIC SRAM Macros",
        "claim": "OpenRAM SRAM macros integrated for SkyWater 130nm tapeout",
        "claimed_value": "29 preserved SRAM macros ($mem_v2) with OpenRAM wrapper",
        "source": "hardware/asic/sky130_sram_macros.v",
        "reproduction_command": "python -c \"import json; d=json.load(open('results/asic_synth.json')); print('Physical macros:', d['physical_macros_present'], 'Notes:', d['audit_notes']['sram_reality'])\"",
        "expected_result": "Physical LEF, LIB, GDS, and SPICE netlists present and accepted by OpenLane",
        "actual_result": "Behavioral Verilog simulation model only (`ifndef SYNTHESIS); zero LEF/LIB/GDS/SPICE exist",
        "evidence_tier": "SIMULATED (Behavioral Wrapper Only)",
        "hardware_verified": False,
        "status": "BLOCKED_FOR_TAPEOUT",
        "notes": "OpenLane will error on placement without compiled OpenRAM macro LEF/LIB files."
    },
    {
        "claim_id": "CLM-10",
        "category": "ASIC Synthesis",
        "claim": "SkyWater 130nm ASIC gate-level synthesis passed with 1,383 standard cells",
        "claimed_value": "1,383 logic cells",
        "source": "results/asic_synth.json generated by hardware/asic/synth_asic.py",
        "reproduction_command": "python -c \"import json; d=json.load(open('results/asic_synth.json')); print('Generic cells:', d['generic_rtlil_cells'], 'Mapped:', d['standard_cell_tech_mapped'])\"",
        "expected_result": "1,383 sky130_fd_sc_hd standard cells mapped via ABC with standard cell area",
        "actual_result": "1,383 unmapped Yosys generic RTLIL AST primitives ($add, $mux, $sdff, $mem_v2)",
        "evidence_tier": "SYNTHESIZED (GENERIC RTLIL ELABORATION ONLY)",
        "hardware_verified": False,
        "status": "ELABORATION_ONLY (NOT CELL MAPPED)",
        "notes": "No ABC Liberty mapping was executed; physical standard-cell area (um2) is unknown."
    },
    {
        "claim_id": "CLM-11",
        "category": "RTL Functional & Hardware E2E Verification",
        "claim": "RailNet RTL passes functional verification and cycle-accurate hardware tests",
        "claimed_value": "10/10 hardware e2e and unit tests pass with zero failures",
        "source": "pytest test suite across tests/hardware/test_pcie_end_to_end.py",
        "reproduction_command": "pytest tests/hardware/test_pcie_end_to_end.py -v",
        "expected_result": "10/10 hardware prototype tests pass",
        "actual_result": "10/10 hardware e2e tests pass (Bit-exact numerical contract, backpressure stalls, bubbles, soft reset, K=8/16/32, sustained 5-token stress, dual-clock CDC)",
        "evidence_tier": "SIMULATED (Cycle-Accurate Hardware Simulation)",
        "hardware_verified": True,
        "status": "VERIFIED_IN_SIMULATION",
        "notes": "Cycle-accurate hardware contracts verified; zero bit error against CPU golden model."
    },
    {
        "claim_id": "CLM-12",
        "category": "CDC & Reset Safety",
        "claim": "Programming bus multi-bit skew eliminated via atomic Gray-coded AsyncFIFO",
        "claimed_value": "Zero multi-bit bus skew hazards across 50 MHz host to 200 MHz core",
        "source": "hardware/rtl/cdc.py ProgCDCFIFO",
        "reproduction_command": "python -c \"from tests.unit.test_cdc_dual_clock import test_axis_cdc_fifo_data_integrity; test_axis_cdc_fifo_data_integrity(); print('CDC Gray FIFO: PASSED')\"",
        "expected_result": "5 CDC unit tests pass verifying FIFO data integrity and backpressure",
        "actual_result": "5/5 CDC tests pass; Gray-coded FIFO eliminates bus skew in simulation",
        "evidence_tier": "SIMULATED (CDC RTL Verification)",
        "hardware_verified": True,
        "status": "VERIFIED_IN_SIMULATION",
        "notes": "Physical hold violations and CTS skew must be verified during physical P&R."
    },
    {
        "claim_id": "CLM-13",
        "category": "PPA Die Sizing",
        "claim": "Gemma3 1B model requires 2 chiplets (572 mm2 total silicon) in commercial 22nm eReRAM",
        "claimed_value": "572.0 mm2 (2 chiplets @ 286 mm2)",
        "source": "hardware/research/ppa_model.py evaluate_die_sizing('gemma3_1b', 'railnet_reram_commercial')",
        "reproduction_command": "python hardware/research/ppa_model.py",
        "expected_result": "Model reports 572.0 mm2 and 2 chiplets",
        "actual_result": "572.0 mm2 and 2 chiplets confirmed; monolithic die is physically unmanufacturable",
        "evidence_tier": "MODELLED (Commercial Silicon Density Basis)",
        "hardware_verified": False,
        "status": "MODELLED_AND_VERIFIED",
        "notes": "Proves multi-chiplet packaging is a mandatory architectural requirement for RailNet."
    },
    {
        "claim_id": "CLM-14",
        "category": "Inference Token Latency",
        "claim": "RailNet achieves 100 tokens/sec sustained generation throughput",
        "claimed_value": "100.0 tokens/sec (10.0 ms/token)",
        "source": "hardware/research/ppa_model.py evaluate_energy_and_power(tokens_per_sec=100.0)",
        "reproduction_command": "python hardware/research/ppa_model.py",
        "expected_result": "Internal bandwidth requirement calculated at 134.2 GB/s for Gemma 1B",
        "actual_result": "Bandwidth calculated at 134.2 GB/s; throughput is an architectural model assumption",
        "evidence_tier": "THEORETICAL (SYSTEM THROUGHPUT TARGET)",
        "hardware_verified": False,
        "status": "ASSUMPTION_DOWNGRADED",
        "notes": "Real token throughput requires measured memory bandwidth on physical silicon or FPGA."
    },
    {
        "claim_id": "CLM-15",
        "category": "Multi-Model Fleet TCO",
        "claim": "RailNet reduces 5-model fleet TCO by $33.6M compared to Taalas fixed ROM",
        "claimed_value": "$33.6M fleet savings ($9.8M vs $43.5M)",
        "source": "hardware/research/ppa_model.py evaluate_fleet_tco(num_models=5, chips_per_model=2000)",
        "reproduction_command": "python hardware/research/ppa_model.py",
        "expected_result": "Savings calculated as $33.6M due to eliminating 5x $8M mask set NRE",
        "actual_result": "Confirmed: Taalas requires 5 separate mask sets ($40M NRE); RailNet requires 1 mask set ($8.5M NRE)",
        "evidence_tier": "MODELLED (Financial NRE / TCO Model)",
        "hardware_verified": False,
        "status": "MODELLED_AND_VERIFIED",
        "notes": "Mathematical proof of the reprogramming thesis: amortizing NRE across multiple models."
    },
    {
        "claim_id": "CLM-16",
        "category": "Stage-B Saturation Clamp",
        "claim": "Stage-B saturation clamp [-2^31, 2^31 - 1] prevents overflow without precision degradation",
        "claimed_value": "0.0% clamp rate under normal LLM activations",
        "source": "benchmarks/benchmark_hardware_bottlenecks.py benchmark_saturation_clamp()",
        "reproduction_command": "python benchmarks/benchmark_hardware_bottlenecks.py",
        "expected_result": "0.0% clamp rate under normal and outlier activation distributions",
        "actual_result": "0.0% clamp rate confirmed (Max accumulator 167.1M vs 2.14B clamp limit)",
        "evidence_tier": "SIMULATED (Monte Carlo Distribution Simulation)",
        "hardware_verified": True,
        "status": "VERIFIED_IN_SIMULATION",
        "notes": "Symmetric clamping protects against sign-inversion overflow while preserving exact dynamic range."
    }
]


def run_reproduction(cmd: str) -> tuple[int, str]:
    """Execute a reproduction command and capture return code and output."""
    if not cmd or cmd.startswith("None") or cmd.startswith("cat"):
        return 0, "N/A (Command not available)"
    try:
        # If standard python script invocation
        parts = cmd.split()
        if parts[0] == "python":
            if parts[1] == "-c":
                # python -c "code"
                code_str = cmd[cmd.find("-c") + 2:].strip().strip('"').strip("'")
                args = [sys.executable, "-c", code_str]
            elif parts[1] == "-m":
                args = [sys.executable] + parts[1:]
            else:
                script_path = str(ROOT / parts[1])
                args = [sys.executable, script_path] + parts[2:]
        elif parts[0] == "pytest":
            args = [sys.executable, "-m", "pytest"] + parts[1:]
        else:
            args = cmd

        proc = subprocess.run(
            args,
            cwd=str(ROOT),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=120
        )
        return proc.returncode, proc.stdout.strip()
    except subprocess.TimeoutExpired:
        return -1, "TIMEOUT (Exceeded 120s)"
    except Exception as e:
        return -2, f"EXECUTION ERROR: {e}"


def run_full_verification_matrix():
    print("=" * 110)
    print("  RAILNET CLAIM-TO-EVIDENCE VERIFICATION & REPRODUCIBILITY AUDIT")
    print("  Standard: Strict 7-Tier Evidence Hierarchy (CLAIM -> EVIDENCE -> REPRODUCTION -> RESULT -> TIER -> STATUS)")
    print("=" * 110)

    results_table = []

    for item in CLAIMS_DATABASE:
        cid = item["claim_id"]
        claim_title = item["claim"]
        tier = item["evidence_tier"]
        status = item["status"]
        cmd = item["reproduction_command"]

        print(f"\n[{cid}] {claim_title}")
        print(f"  Claimed Value:    {item['claimed_value']}")
        print(f"  Evidence Tier:    {tier}")
        print(f"  Reproduction:     {cmd}")

        # Test execution if reproducible
        out = ""
        if cmd and not cmd.startswith("None") and not cmd.startswith("cat"):
            t0 = time.time()
            rc, out = run_reproduction(cmd)
            elapsed = time.time() - t0
            exec_status = "PASS" if rc == 0 else f"FAIL (code {rc})"
            print(f"  Execution:        {exec_status} ({elapsed:.2f}s)")
            item["reproduction_exit_code"] = rc
            item["reproduction_elapsed_sec"] = round(elapsed, 2)
        else:
            item["reproduction_exit_code"] = None
            item["reproduction_elapsed_sec"] = None
            print("  Execution:        SKIPPED (Static inspection or missing EDA tool)")

        # What this run observed must be derived from this run. Printing the
        # stored prose regardless of the exit code reported failed reproductions
        # as confirmations.
        rc_now = item["reproduction_exit_code"]
        if rc_now is None:
            item["reproduced"] = None
            observed = "NOT RUN (no executable reproduction command)"
        elif rc_now == 0:
            item["reproduced"] = True
            observed = out.strip().splitlines()[-1] if out.strip() else "(command produced no output)"
        else:
            item["reproduced"] = False
            tail = out.strip().splitlines()[-1] if out.strip() else "(no output)"
            observed = f"NOT REPRODUCED (exit {rc_now}): {tail}"
        item["observed_this_run"] = observed
        # This project owns no board, no PDK and no silicon, so nothing here can
        # sit at Tier 6/7. Synthesis and P&R are tool output, not measurement.
        item["hardware_verified"] = False

        print(f"  Expected Result:  {item['expected_result']}")
        print(f"  Observed This Run:{observed}")
        print(f"  Recorded Earlier: {item['actual_result']}")
        print(f"  Current Status:   {status}")
        results_table.append(item)

    out_file = ROOT / "results" / "claim_verification_matrix.json"
    out_file.parent.mkdir(exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(results_table, f, indent=2)

    print("\n" + "=" * 110)
    print("  VERIFICATION MATRIX SUMMARY")
    print("=" * 110)
    print(f"{'ID':<8} {'Evidence Tier':<35} {'Hardware Verified':<20} {'Status':<30}")
    print("-" * 110)
    for r in results_table:
        hw_str = "YES" if r["hardware_verified"] else "NO (UNVERIFIED)"
        print(f"{r['claim_id']:<8} {r['evidence_tier']:<35} {hw_str:<20} {r['status']:<30}")

    print("\n" + "=" * 110)
    print(f"Complete audited verification matrix written to: {out_file}")
    print("=" * 110)
    return 0


if __name__ == "__main__":
    sys.exit(run_full_verification_matrix())
