# =============================================================================
# RailNet FPGA Constraints for QMTech Xilinx Artix-7 XC7A35T/100T PCIe Board
# Target Package: FGG484 (-1 speed grade)
# PCIe Specification: Gen2 x1 Endpoint with LitePCIe / XDMA
# =============================================================================

# -----------------------------------------------------------------------------
# Configuration Bank Voltage Select (CFGBVS)
# -----------------------------------------------------------------------------
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# -----------------------------------------------------------------------------
# Onboard System Clock (50 MHz Single-Ended Oscillator)
# -----------------------------------------------------------------------------
set_property PACKAGE_PIN M21 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

# -----------------------------------------------------------------------------
# PCIe Fundamental Reset (PERST# from PCIe Edge Connector)
# Active-Low, 3.3V LVCMOS with internal pull-up
# -----------------------------------------------------------------------------
set_property PACKAGE_PIN J20 [get_ports pcie_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_rst_n]
set_property PULLUP true [get_ports pcie_rst_n]
set_false_path -from [get_ports pcie_rst_n]

# -----------------------------------------------------------------------------
# PCIe Reference Clock (100 MHz HCSL Differential Pair on GTP Quad 216)
# -----------------------------------------------------------------------------
set_property PACKAGE_PIN F6 [get_ports pcie_refclk_p]
set_property PACKAGE_PIN E6 [get_ports pcie_refclk_n]
create_clock -period 10.000 -name pcie_refclk [get_ports pcie_refclk_p]

# -----------------------------------------------------------------------------
# PCIe Gen2 Lane 0 Serial Transceiver Pins (GTP Quad 216 Channel 0)
# -----------------------------------------------------------------------------
set_property PACKAGE_PIN B4 [get_ports pcie_rx_p]
set_property PACKAGE_PIN A4 [get_ports pcie_rx_n]
set_property PACKAGE_PIN B8 [get_ports pcie_tx_p]
set_property PACKAGE_PIN A8 [get_ports pcie_tx_n]

# -----------------------------------------------------------------------------
# Status Diagnostic LEDs (Active-High, LVCMOS33)
#   debug_leds[0]: DMA H2C streaming active (data transferring into card)
#   debug_leds[1]: DMA C2H streaming active (data transferring back to host)
#   debug_leds[2]: Frame completion interrupt active
#   debug_leds[3]: PCIe link / reset status (alive heartbeat)
# -----------------------------------------------------------------------------
set_property PACKAGE_PIN E22 [get_ports {debug_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[0]}]
set_property DRIVE 8 [get_ports {debug_leds[0]}]
set_property SLEW SLOW [get_ports {debug_leds[0]}]

set_property PACKAGE_PIN D22 [get_ports {debug_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[1]}]
set_property DRIVE 8 [get_ports {debug_leds[1]}]
set_property SLEW SLOW [get_ports {debug_leds[1]}]

set_property PACKAGE_PIN G21 [get_ports {debug_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[2]}]
set_property DRIVE 8 [get_ports {debug_leds[2]}]
set_property SLEW SLOW [get_ports {debug_leds[2]}]

set_property PACKAGE_PIN G22 [get_ports {debug_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debug_leds[3]}]
set_property DRIVE 8 [get_ports {debug_leds[3]}]
set_property SLEW SLOW [get_ports {debug_leds[3]}]

set_false_path -to [get_ports {debug_leds[*]}]

# -----------------------------------------------------------------------------
# Clock Domain Crossing (CDC) Timing Constraints
# pcie_clk (62.5 / 125 MHz, LitePCIe user_clk) <-> core_clk (80-100 MHz MMCM)
# are asynchronous. All crossings use Gray-coded AsyncFIFO in hardware/rtl/cdc.py
# (AxisCDCFIFO + AxiLiteCDCBridge) and FFSynchronizer for IRQ.
# pcie_clk is generated by PCIe hard IP (GT) / LitePCIe, core_clk by MMCM.
# Both are asynchronous to sys_clk and to each other.
# -----------------------------------------------------------------------------
# Virtual clock definitions (will be overridden by IP-generated clocks after synthesis)
# These ensure Vivado timing analysis does not optimistically assume synchrony.
create_clock -period 16.000 -name pcie_clk [get_ports pcie_clk]  ;# 62.5 MHz default (125 MHz also valid)
create_clock -period 10.000 -name core_clk [get_ports core_clk]  ;# 100 MHz core (80-100 MHz range)

set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks pcie_clk] \
    -group [get_clocks -include_generated_clocks core_clk]

set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks sys_clk] \
    -group [get_clocks -include_generated_clocks pcie_refclk]

set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks sys_clk] \
    -group [get_clocks -include_generated_clocks core_clk]

# PCIe hard IP GT reference clock is asynchronous to fabric clocks
set_clock_groups -asynchronous \
    -group [get_clocks pcie_refclk] \
    -group [get_clocks pcie_clk]

# -----------------------------------------------------------------------------
# Bitstream Generation Settings
# -----------------------------------------------------------------------------
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
